#!/usr/bin/env bash
echo $BASH_VERSION
n=1; echo -n "$n"

((n = $n + 1))
echo -n "$n"

a=25
b=47

if [ "$a" -eq 25 ] && [ "$b" -eq 47 ]
then
  echo "Test succeeded $a and $b"
else
  echo "Test failed"
fi
