#!/usr/bin/env bash
#Integrated script
echo $$ >> /var/run/myscript.pid

n=1
while (( n==1 )); do
   echo "To infinity and beyond"
done

trap "{ echo 'I hate the kill command'; }" SIGTERM
trap "{ echo 'Y U no love me?!'; }" SIGINT
trap "{ rm /var/run/myscript.pid; }" SIGQUIT SIGTERM
