#!/usr/bin/env bash
#Print FizzBuzz numbers
i="1"
while (( i < "101" ));
do
   if [ "$((i%3))" -eq 0 ];
   then
      if [ $"$((i%5))" -eq 0 ];
      then
         echo "FizzBuzz"
      else
         echo "Fizz"
      fi
      i=$((i+1))
   elif [ "$((i%5))" == 0 ];
   then
      echo "Buzz"
      i=$((i+1))
   else
      echo "$i"
      i=$((i+1))
   fi
done
