#!/usr/bin/env bash
#This script prints "Best School"
i="0"
while (( i < 10 ));
do
     if [ $i -ne 8 ];
     then
          echo "Best School"
          i=$((i+1))
     else
          echo "Best School"
	  echo "Hi"
	  i=$((i+1))
     fi
done
