#!/usr/bin/env bash
#This script prints "Best School"
i="1"
while (( i < 21 ));
do
     case $i in

     4)
          echo "4"
          echo "bad luck from China"
          i=$((i+1))
	  ;;

     9)
          echo "9"
          echo "bad luck from Japan"
	  i=$((i+1))
	  ;;
     17)
          echo "17"
          echo "bad luck from Italy"
          i=$((i+1))
	  ;;
     *)
          echo "$i"
	  i=$((i+1))
	  ;;
     esac
done
