#!/usr/bin/env bash
#This script prints "Best School"
i="0"
j="0"
while (( i < 13 ));
do
     echo "Hour: $i"
     while (( j < 60));
     do
          j=$((j+1))
          echo $j
     done
     j="0"
     i=$((i+1))
done
