#!/usr/bin/env bash
#Prints file information

file="school"
if [ -e "$file" ]
then
   echo "$file file exists"
   if [ -f "$file" ]
   then
      echo "$file is a regular file"
   fi

   if [ -s "$file" ]
   then
      echo "school file is not empty"
   else
      echo "school file is empty"
   fi

else
   echo "$file file does not exist"
fi
